### ISSUE TITLE
Root key rollover support

### ISSUE THREAD

**Issue by ralfhauser** [ibauersachs/dnssecjava#11]
as took place today (https://www.iana.org/dnssec/files, https://www.heise.de/newsticker/meldung/DNS-Schluesselwechsel-Am-11-10-ist-es-so-weit-4179863.html)

ValidatingResolver.loadTrustAnchors(InputStream data)
so far took 
   ". IN DS 19036 8 2 49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5"

and since today, it needs
  ". IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d"
  
Is it possible to just concatenate the 2 Strings with LF, or is there further potential for smooth roll-over support ?

**Comment by ralfhauser** [comment]
https://www.internetsociety.org/blog/2018/10/are-you-ready-how-to-prepare-for-the-dnssec-root-ksk-rollover-on-october-11-2018/

**Comment by ibauersachs** [comment]
Yes, you can load as many DS records as you want, one per line. I'm not aware of a library that would handle key rollover per the newer RFCs. Since the storage of the keys is application specific, it wouldn't make much sense to include this here as well.

**Comment by ralfhauser** [comment]
Thx - 
1) What's in your opinion the best way to learn about new DS records as they come up ?
a) does your project have a corresponding mailing list where such announcements would be seen ?
2) Apparently, the old root key signs the new one - does your code support the validation of based on that ?

**Comment by ibauersachs** [comment]
IANA publishes the official keys at https://www.iana.org/dnssec/files. The KSK rollover from last Thursday was common knowledge since about two years.
[RFC 5011](https://tools.ietf.org/html/rfc5011) specifies an automated method to keep the records up to date. I'm not aware of a Java library implementing the protocol. On a server application you could probably reuse the downloaded keys from a BIND or Unbound installation - or just do it manually for the time being, the last KSK rollover was 2010.

This library could do the actual DS key validation, but it doesn't implement the hold-down requirements of RFC 5011.
